#!/bin/bash


#!/bin/sh

ProgName=$(basename $0)

FS_CHALLENGER=/home/challenger/rlberry-farms/farmscool_challenger
DATA_DIR=/mnt/data/challenge
login=$(whoami)
timestamp=$(date +%s)

sub_help(){
    echo "Usage: $ProgName <subcommand> [options]"
    echo ""
    echo "Subcommands:"
    echo "    add               Add script to queue"
    echo "    log               View the logs of current job "
    echo "    leaderboard       Print current leaderboard"
    echo "    info              See queue"
    echo "    suspend           Suspend queue"
    echo "    resume            Resume queue"
    echo "    play              Play manually."
    echo "    top               Display all jobs and kill them if necessary."
    echo "    "
    echo ""
    echo "For help with each subcommand run:"
    echo "$ProgName <subcommand> -h|--help"
    echo ""

}

sub_add(){
    case $1 in  "" | "-h" | "--help")
                   echo "Usage: $ProgName add <python_file.py> <n_fit>"
                   echo ""
                   echo "    Add your agent to the queue in the challenge."
                   echo ""
                   echo "    Parameters:"
                   echo "       python_file: a .py file containing a rlberry agent class called \"Agent\"."
                   echo "       n_fit: an int, number of steps to train for."
                   echo ""
                   echo "    Example:"
                   echo "       $ProgName add ppo.py 10000"
                   echo ""
                   echo "       where ppo.py contain the following:"
                   echo ""
                   echo "from rlberry.agents import PPOAgent"
                   echo "class Agent(PPOAgent):"
                   echo "    def __init__(self, env, **kwargs):"
                   echo "        PPOAgent.__init__(self, env, **kwargs)"
                   echo "        self.batch_size = 16"
                   echo "        self.gamma = 0.9"

                   ;;
                   *)
                       cp $(realpath $1) $DATA_DIR/scripts/script-$login-$timestamp.py
                       cp $(realpath $1) $DATA_DIR/latest_script.py

                       sudo -u challenger $FS_CHALLENGER add $2 $login
                       ;;
     esac
}



subcommand=$1
case $subcommand in
    "" | "-h" | "--help")
        sub_help
        ;;
    add)
        shift
        sub_add $@
        ;;
    *)
        shift
        sudo -u challenger $FS_CHALLENGER $subcommand $@
        ;;
esac
