#!/bin/bash

# Application on which we give sudo rights. Used to interact with singularity.

ProgName=$(basename $0)
DATA_DIR=/mnt/data/challenge

sub_help(){
    echo "Usage: $ProgName <subcommand> [options]"
    echo ""
    echo "Subcommands:"
    echo "    add               Add script to queue"
    echo "    log               View the logs of current job "
    echo "    leaderboard       Print current leaderboard"
    echo "    info              See queue"
    echo "    suspend           Suspend queue"
    echo "    resume            Resume queue"
    echo "    play              Play manually."
    echo "    top               Display all jobs and kill them if necessary."
    echo "    "
    echo ""
    echo "For help with each subcommand run:"
    echo "$ProgName <subcommand> -h|--help"
    echo ""

}

sub_add(){
    case $1 in  "" | "-h" | "--help")
                   echo "Usage: $ProgName add <python_file.py> <n_fit>"
                   echo ""
                   echo "    Add your agent to the queue in the challenge."
                   echo ""
                   echo "    Parameters:"
                   echo "       python_file: a .py file containing a rlberry agent class called \"Agent\"."
                   echo "       n_fit: an int, number of steps to train for."
                   echo ""
                   echo "    Example:"
                   echo "       $ProgName add ppo.py 10000"
                   echo ""
                   echo "       where ppo.py contain the following:"
                   echo ""
                   echo "from rlberry.agents import PPOAgent"
                   echo "class Agent(PPOAgent):"
                   echo "    def __init__(self, env, **kwargs):"
                   echo "        PPOAgent.__init__(self, env, **kwargs)"
                   echo "        self.batch_size = 16"
                   echo "        self.gamma = 0.9"

                   ;;
                   *)
                       singularity run instance://challenge  add $DATA_DIR/latest_script.py $2 $3
                       ;;
     esac
}


sub_activate(){
    case $1 in "-h" | "--help")
                   echo "Usage: $ProgName activate"
                   echo ""
                   echo "    Activate the virtual environment used in the challenge."
                   echo ""

                   ;;
                   *)
                       singularity shell instance://challenge
                       ;;
     esac
}


subcommand=$1
case $subcommand in
    "" | "-h" | "--help")
        sub_help
        ;;
    add)
        sub_add $@
        ;;
    activate)
        sub_activate
        ;;
    *)
        shift
         singularity run --pid instance://challenge ${subcommand} $@
        ;;
esac
